[HTTP]
HTTPServerEnabled = false
UseSSL = false
HTTPServerIP = "0.0.0.0"
HTTPServerPort = 30815
SSLCertPath = "./.ssl/HttpServer/cert.pem"
SSLKeyPath = "./.ssl/HttpServer/key.pem"

[Misc]
SendErrorsShowMessage = true
SendErrors = true
ImScaredOfUpdates = false

[General]
Description = "BeamMP Default Description"
ResourceFolder = "Resources"
Map = "/levels/gridmap_v2/info.json"
MaxPlayers = 8
Port = 30814
Private = true
Debug = false
Name = "AMP Powered BeamMP Server"
LogChat = true
MaxCars = 1
AuthKey = ""
