java_edition = true
java_edition_address = "0.0.0.0:25565"
bedrock_edition = true
bedrock_edition_address = "0.0.0.0:19132"
seed = ""
max_players = 1000
view_distance = 16
simulation_distance = 10
default_difficulty = "Normal"
op_permission_level = 4
allow_nether = true
allow_end = true
hardcore = false
online_mode = true
encryption = true
motd = "A blazingly fast Pumpkin server!"
tps = 20.0
default_gamemode = "Survival"
force_gamemode = false
scrub_ips = true
use_favicon = true
favicon_path = "icon.png"
default_level_name = "world"
allow_chat_reports = false
white_list = false
enforce_whitelist = false
