---
  name: Validate JSON Schemas
  
  on: # yamllint disable-line rule:truthy
    workflow_dispatch:
    pull_request:
    push:
      branches: [ "dev" ]
  
  permissions: read-all
  
  jobs:
    validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: "Validate manifest.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: 'manifest.json'
            schema: schemas/manifest.schema.json
            fixSchemas: true
  
        - name: "Validate *.config.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.config.json'
            schema: schemas/config.schema.json
            fixSchemas: true
  
        - name: "Validate *.metaconfig.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.metaconfig.json'
            schema: schemas/metaconfig.schema.json
            fixSchemas: true
  
        - name: "Validate *.updates.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.updates.json'
            schema: schemas/updates.schema.json
            fixSchemas: true
  
        - name: "Validate *.ports.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.ports.json'
            schema: schemas/ports.schema.json
            fixSchemas: true
  
        - name: "Validate *.generator.json"
          uses: cardinalby/schema-validator-action@v3 # walbo/validate-json@v1.1.0
          with:
            # files: "*.generator.json"
            file: '*.generator.json'
            schema: schemas/generator.schema.json
            mode: spec
            fixSchemas: true
            # schema-version: draft-06
            # strict: false
            # allow-matching-properties: true
            # allow-union-types: true
            # print-valid-files: false
              
              
              